### ISSUE TITLE
Get Admin Access to our Account(s)

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-crm#1]
For: @edrushka @valianttry @adamlofting

**Comment by edrushka** [comment]
Heh. I love that this is the first issue in the repo ;)

**Comment by edrushka** [comment]
@adamlofting Can you create a dev account (either one for all Mofo Devs, although Sean recommended against this or at least one for @alicoding). We need @ScottDowne and Ali to be able to get in and look around.

**Comment by adamlofting** [comment]
I've created accounts for @alicoding and @ScottDowne in the grants/partners instance of salesforce. You should both have emails about this now. This will be a different instance of Salesforce to any that you used for ExactTarget training last week.

I think this hits the max limit for our current salesforce licences right now, but we need to resolve all of that soon.

**Comment by adamlofting** [comment]
After talking to @alicoding in IRC, it seems you already have accounts so I've deactived the two new ones that I setup today.

Please continue to use the existing accounts :+1:
