### ISSUE TITLE
Setup Salesforce for Cecile and Bhuvan

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-crm#20]
...to track partnerships and opportunities.

cc @bhuvanshri

@cecilepompei - I was just talking to Bhuvan and heard you are collecting partnership data which would be useful to store in a CRM. For now, keep using your existing spreadsheet, but over the next couple of weeks let's get you setup in Salesforce so you can use that instead.

Is the spreadsheet a google doc, and if so, could you share with me so I can get an idea of the type of data you're recording?

**Comment by bhuvanshri** [comment]
This is the document that we are currently using to track external consultations for the Learning strategy - horrible, I know! https://docs.google.com/spreadsheets/d/1dGb3Lo7nZjaH0SLT-mbPQpWsfqY4l6a1x7oOAspkimk/edit?usp=sharing

I didn't want to put too much effort into it at the time. I would love to see the Salesforce templates available that we can use for this file too. I would say this is not as high a priority as what @cecilepompei may need.

**Comment by cecilepompei** [comment]
Hey,

I already file everything onto Sales Force (feeling like a Saint now!)

I am working on partnerships and organizing them around the different
streams of what is needed.
      - on the one hand providing intelligence for the various teams and
working groups based on the partner interviews
     - doing some business development / signing deals for the various
teams: webmaker (more content creation workhsops), clubs (finding RC and
clubs), working groups (finding a way to partner for the future projects of
Mozilla)

I find Sales Force not super amazing for all of this, so it is more to
record the deals that I use it , and i have excel for the rest!

On Wed, Jul 15, 2015 at 8:19 PM, Bhuvan Shrivastava <
notifications@github.com> wrote:

> This is the document that we are currently using - horrible, I know!
> https://docs.google.com/spreadsheets/d/1dGb3Lo7nZjaH0SLT-mbPQpWsfqY4l6a1x7oOAspkimk/edit?usp=sharing
> 
> I didn't want to put too much effort into it at the time. I would love to
> see the Salesforce templates available that we can use for this file too. I
> would say this is not as high a priority as what @cecilepompei
> https://github.com/cecilepompei may need.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/mofo-crm/issues/20#issuecomment-121684861
> .

## 

Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by adamlofting** [comment]
Excellent news!

Hopefully we can make Salesforce easier to use for the things currently in Excel.

**Comment by cecilepompei** [comment]
let us know what we can do to help design this!

On Mon, Jul 20, 2015 at 12:23 PM, Adam Lofting notifications@github.com
wrote:

> Excellent news!
> 
> Hopefully we can make Salesforce easier to use for the things currently in
> Excel.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/mofo-crm/issues/20#issuecomment-122822223
> .

## 

Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by bhuvanshri** [comment]
@cecilepompei - You might be able to share the file that you are currently using to keep your notes in excel. If we have that template set up in Salesforce, more people would be able to use it (like me)!

**Comment by bhuvanshri** [comment]
@adamlofting Could I get access to Salesforce? I would like to see what's already available to be able to better advice if there is something specific I need your assistance with.

**Comment by adamlofting** [comment]
Going to close this ticket for now, as you both have access to Salesforce, and you're on the two week trial for Cirrus Insights starting from Monday.

However, this isn't the end of the CRM conversation, so please keep sending me feedback about what is and isn't working well for you.
