### ISSUE TITLE
Build / Setup Email Templates within ExactTarget

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-crm#9]
Depends on [Review existing email templates in use in BSD](https://github.com/MozillaFoundation/mofo-crm/issues/8).

Requirements to follow.

**Comment by adamlofting** [comment]
We will need:
- Basic Mozilla template like the one we currently use
- Plain emails (no branding)
- Basic webmaker email

**Comment by jessilyndavis** [comment]
To get started creating Templates inside of ExactTarget, I offer you the following resources:

1) Example template for Firefox + You:

```
Login to ExactTarget, click on "Email" in top nav.
Content > My Templates > Firefox & You
explore this parent folder, and then the subfolders.
Feel free to make copies of these items to play with (please do not edit/save on the originals here)
```

2) Example templatized story "Content" blocks that are used in Firefox + You template when creating email:

```
Login to ExactTarget, click on "Email" in top nav.
Content > My Contents > Firefox & You
explore this parent folder, and then the subfolders.
Feel free to make copies of these items to play with (please do not edit/save on the originals here)
```

2) Example of email created using said template:

```
Content > My Emails > Firefox & You > "Sample Email using Firefox + You EN template"
```

3) Helpful help docs:

```
http://help.exacttarget.com/en-US/documentation/exacttarget/content/email_overview/creating/how_to_build_a_template_based_email/
http://help.exacttarget.com/en-US/documentation/exacttarget/content/email_overview/content_boxes/
http://help.exacttarget.com/en-US/documentation/exacttarget/content/templates/
```

If it's helpful, I'd be happy to meet and help assist with setting the first Foundation template up (we'll need an HTML file to work with). I'm thinking you can create new Templates and emails in new folders under "My Emails" and "My templates" as part of the "Foundation" Account.

Holler at me with your questions.

**Comment by jessilyndavis** [comment]
Happy Friday! Your templates are ready :)

You can find them in ExactTarget:

Email Module > Content tab > Shared Templates (folder on left) > Foundation

And sample emails created with them in the "Mozilla Foundation" Business Unit (look in your top right hand corner when you log in to see what Buisness Unit you're in and click on it to switch):

Email Module > Content tab > My Emails

Let me know if you'd like me to show you around.
